import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Math App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="flex flex-col items-center justify-center w-full">
          <div className="w-[95%] md:w-[90%] lg:w-[85%]">{children}</div>
        </main>
      </body>
    </html>
  );
}
