import type { Metadata } from "next";
import "./globals.css";
import "katex/dist/katex.min.css";
import { Toaster } from "react-hot-toast";
import { AppContextProvider } from "@/hooks/useApp";
import { ModalContextProvider } from "@/hooks/useModal";
import { TrainContextProvider } from "@/hooks/useTrain";
import { AIChatContextProvider } from "@/hooks/useAIChat";
import { ThreadContextProvider } from "@/hooks/useThreads";

export const metadata: Metadata = {
  title: "Math App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col items-center justify-center w-full">
          <ThreadContextProvider>
            <AIChatContextProvider>
              <ModalContextProvider>
                <TrainContextProvider>
                  <AppContextProvider>
                    {children}
                    <Toaster
                      position="top-center"
                      toastOptions={{
                        className: "z-[10000]",
                        style: {
                          zIndex: 10000,
                        },
                      }}
                    />
                  </AppContextProvider>
                </TrainContextProvider>
              </ModalContextProvider>
            </AIChatContextProvider>
          </ThreadContextProvider>
        </main>
      </body>
    </html>
  );
}
