import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppContextProvider } from "@/hooks/useApp";

export const metadata: Metadata = {
  title: "Math App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col items-center justify-center w-full">
          <AppContextProvider>
            {children}
            <Toaster position="top-center" />
          </AppContextProvider>
        </main>
      </body>
    </html>
  );
}
